# Generated by Django 5.1.1 on 2024-10-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='headline',
            new_name='title',
        ),
    ]
