# Generated by Django 4.2.7 on 2024-10-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_username_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='user', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
