# Generated by Django 4.2.7 on 2024-10-16 08:12
from django.db import migrations

def assign_unique_usernames(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    for user in CustomUser.objects.filter(username__isnull=True):
        user.username = f'user_{user.id}'  # Générer un nom d'utilisateur unique basé sur l'ID de l'utilisateur
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        # Ajoute ici la dépendance à ta dernière migration
        ('users', '0003_customuser_username_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.RunPython(assign_unique_usernames),
    ]
