# Generated by Django 4.2.7 on 2024-10-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_username'),
        ('users', '0005_auto_20241016_0812'),
    ]

    operations = [
    ]
